name: Build QMK Firmware
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up QMK
      uses: qmk/qmk-cli-action@v2
    - run: qmk compile -kb darkproject/alu81a -km default
    - uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: "*.hex"